services:
  - type: web
    name: ngo-website
    env: static
    buildCommand: cd project && npm install && npm run build
    staticPublishPath: project/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
